---
title: "indicadores"
author: "Andrea Gomez Vargas"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(openxlsx)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# EPH
pobreza <- read.xlsx("data/datos.xlsx", sheet = "pobreza")
estrato <- read.xlsx("data/datos.xlsx", sheet = "estrato")
ingresos  <- read.xlsx("data/datos.xlsx", sheet = "ingresos")

# CAPITAL HUMANO 
bess <- read.xlsx("data/datos.xlsx", sheet = "bess-1")

# CENSO 
salud  <- read.xlsx("data/datos.xlsx", sheet = "salud")
jubilacion <- read.xlsx("data/datos.xlsx", sheet = "jubilacion")
salud2 <- read.xlsx("data/datos.xlsx", sheet = "salud2")
```


## Censo

### Jubilación

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}
jubilacion <- jubilacion %>% 
  mutate(sexo = factor(sexo, levels = c("total", "mujeres", "varones")),
         cobertura = case_when(
           sexo == "total" ~ "Población en edad de jubilarse",
           sexo == "mujeres" ~ "Mujeres de 60 años y más",
           sexo == "varones" ~ "Varones de 65 años y más"),
         cobertura = fct_relevel(cobertura, c("Población en edad de jubilarse", 
                                              "Mujeres de 60 años y más", 
                                              "Varones de 65 años y más")))

ggplot(jubilacion, aes(cobertura, porcentaje, fill = sexo)) +
  geom_col(width = 0.5) +
  ylim(c(0,100)) +
  #scale_fill_manual(values = c("#fb8b24","#d90368","#820263")) +
  scale_fill_manual(values = c("#001524","#3c6e71","#15616d")) +
  theme_bw() +
  theme(
    legend.position = "none"
  ) +
  geom_text(aes(label = porcentaje), 
            position = position_stack(vjust = 0.9), 
            size = 4, colour = "white") +
  labs(
    x = " ",
    y =  "Porcentaje",
    title = "Población en viviendas particulares en edad jubilatoria que percibe jubilación o pensión. \nTotal del país. Año 2022",
    caption = "Fuente: elaboración propia con base en datos del INDEC. Censo Nacional de Población, Hogares y Viviendas 2022."
  )
```

## Salud 


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}

salud2 <- salud2 %>% 
  mutate(pp_obra_social = round(obra_social/poblacion_total*100,2),
         pp_plan_estatal = round(plan_estatal/poblacion_total*100,2),
         pp_no_tiene = round(no_tiene/poblacion_total*100,2)
         ) %>% 
  filter(grupo_edad == "total") %>% 
  select(1, 7:9) %>% 
  pivot_longer(cols = c(2:4),names_to = "tipo", values_to = "value") %>% 
  mutate(tipo = case_when( tipo == "pp_no_tiene" ~ 
                             "No tiene obra social, prepaga ni plan estatal",
                           tipo == "pp_plan_estatal" ~ "Programas o planes estatales de salud",
                           tipo == "pp_obra_social" ~ "Obra social o prepaga (incluye PAMI)")
  )
  

ggplot(salud2, aes(sexo,value, fill = tipo)) +
  geom_col() +
  coord_flip() +
  #scale_fill_viridis_d(option = "a") +
  #scale_fill_manual(values = c("#5e548e","#297373", "#389e9e"))+
  scale_fill_manual(values = c("#f7b801","#7678ed", "#3d348b"))+
  theme_bw() +
  labs(
    title = "Población en viviendas particulares en edad jubilatoria por sexo registrado al nacer según tenencia de cobertura de salud. \nTotal del pais. Año 2022",
    y = "porcentaje",
    caption = "Fuente: elaboración propia con base en datos del INDEC. Censo Nacional de Población, Hogares y Viviendas 2022.",
    x = " "
  ) +
  geom_text(aes(label = value),
            position = position_stack(vjust = .5),size = 4, colour = "black") +
 theme(legend.position = "top")
```

## EPH

### Pobreza


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}

gpobreza <- pobreza %>% 
  select(1:2,5:6) %>% 
  pivot_longer(cols = c(3:4), names_to = "pobreza", values_to = "value") %>% 
  mutate(periodo =  paste0(anio, "-", semestre),
         pobreza = ifelse(pobreza == "no_pobres", "No pobre", "Pobre")) 


ggplot(gpobreza, aes(periodo, value, fill = pobreza)) +
  geom_col() +
  scale_fill_manual(values = c("#297373", "#e9d758")) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  coord_flip() +
  scale_x_discrete(limits=rev) +
  geom_text(aes(label = value, group = pobreza), 
            position = position_stack(vjust = 0.5), 
            size = 3, colour = "black") +
  labs(
    x = "periodo",
    y = "porcentaje",
    fill = "condición",
    title = "Población de 65 años y más según condición de pobreza. Total 31 aglomerados. \nPrimer semestre 2018-segundo semestre 2023",
    caption = "Fuente: elaboración propia con base en datos del INDEC. Informes técnicos EPH: Incidencia de la Pobreza y de la Indigencia"
  )
  
```


### Estrato


```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}

estrato <- estrato %>% 
  filter(Grupo ==  "Total",
         Sexo != "Total") %>% 
  select(1, 3, 9:11) %>% 
  pivot_longer(cols = c(3:5), names_to = "tipo", values_to = "porcentaje")




ggplot(estrato, aes(Sexo, porcentaje, fill = tipo)) +
  geom_col() +
 scale_fill_manual(values = c("#143939","#297373", "#389e9e"))+
 facet_grid(~ANO4) +
#   theme_light() +
  labs(
    title = "Distribución de la población de 60 años y más por sexo,\nsegún estrato generacional del hogar. Total nacional urbano. Años 2018-2023",
    y = "porcentaje",
    caption = "Fuente: elaboración propia con base en datos del INDEC. Encuesta Permanente de Hogares total urbano",
    x = " "
  ) +
  geom_text(aes(label = porcentaje, group = Sexo),
            position = position_stack(vjust = .5),size = 4, colour = "white") +
 theme(legend.position = "top")
```

### Ingresos

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}
ingresos <- ingresos %>% 
  filter(CH04 != "Total") %>% 
  select(1,2, 7:9) %>% 
  pivot_longer(cols = c(3:5), names_to = "tipo", values_to = "porcentaje") %>% 
  mutate(tipo = 
           case_when(tipo == "Ingresos.laborales" ~ "ingresos laborales",
                     tipo == "Jubilación.o.pensión" ~ "jubilación o pensión",
                     tipo == "Otros.ingresos.no.laborales" ~ "otros ingresos no laborales")) %>% 
  rename(ano = "Año", sexo =  CH04)


ggplot(ingresos, aes(ano, porcentaje, group = tipo, colour = tipo)) +
  geom_point(size = 3) +
  geom_line(linetype = 2,linewidth = 1) +
  facet_wrap(~sexo) +
  ylim(c(0,100)) +
  scale_color_manual(values = c("#143939","#297373", "#389e9e"))+
 # facet_grid(ano ~ tipo) +
 theme_bw() +
  labs(
    title = "Porcentaje de población en edad jubilatoria perceptora de ingresos por tipo de ingreso. Total nacional urbano. Años 2018-2023",
    y = "porcentaje",
    caption = "Fuente: elaboración propia con base en datos del INDEC. Encuesta Permanente de Hogares total urbano",
    x = " "
  ) +
  geom_text(aes(label = porcentaje, group = tipo),vjust = -1) +
  # geom_text(aes(label = porcentaje, group = tipo),
  #           position = position_stack(vjust = 1),size = 3, colour = "black") +
 theme(legend.position = "top")

```




## Capital Humano

```{r echo=FALSE, message=FALSE, warning=FALSE, fig.width= 10, fig.height= 5}
gbess <- bess %>% 
  filter(ano %in% c(2018:2023)) %>% 
  mutate(pp_con_v = round(con_moratoria_v/total_v*100,2),
         pp_sin_v = round(sin_moratoria_v/total_v*100,2),
         pp_con_m = round(con_moratoria_m/total_m*100,2),
         pp_sin_m = round(sin_moratoria_m/total_m*100,2)
         ) %>% 
  select(1, 8:11) %>% 
  pivot_longer(cols = c(2:5),names_to = "porcentaje", values_to = "value") %>% 
  mutate(sexo = case_when(porcentaje %in% c("pp_con_m","pp_sin_m") ~ "mujeres",
                          TRUE ~ "varones"),
         jubilacion =  case_when(porcentaje %in% c("pp_con_m","pp_con_v") ~ "con moratoria",
                          TRUE ~ "sin moratoria")
         )


ggplot(gbess, aes(sexo, value, fill = jubilacion))+
  geom_col() +
  facet_wrap(~ ano, nrow = 1) +
  #coord_flip() +
  #scale_fill_brewer(palette = "Set2") +
  scale_fill_manual(values = c("#297373", "#e9d758")) +
  theme_bw() +
  theme(
    legend.position = "top"
  ) +
  geom_text(aes(label = value, group = jubilacion), 
            position = position_stack(vjust = 0.5), 
            size = 3, colour = "black") +
  labs(
    x = " ",
    y = "porcentaje",
    fill = "percepción jubilatoria",
    title = "Distribución porcentual de las jubilaciones del sistema integrado previsional, por sexo y adhesión a moratoria. Total del país. Años 2018-2013",
    caption = "Fuente: elaboración propia con base en datos del Ministerio de Capital Humano - Boletín Estadístico de la Seguridad Social")
```



