---
title: "pirámide poblacional"
author: "agomezvargas"
date: "2024-09-09"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
library(readxl)
library(ggplot2)

options(scipen = 999)

```




```{r DATA, include=FALSE}
datasies <- read_excel("cálculos demografia y salud/PAD_MIG.xlsx", sheet = "TR")


datasies$edad = ifelse(datasies$edad %in% "0-4", "00-04", datasies$edad)
datasies$edad = ifelse(datasies$edad %in% "5-9", "05-09", datasies$edad)


datasies <- datasies %>%
    mutate(censo = as.numeric(censo),
           value = ifelse(sexo == "V", -value, value),
           value = round(value,1))

```



```{r eval=FALSE, include=FALSE}

# plot_ly

pi1914 <- datasies %>% 
  filter(censo == 1914) %>% 
  plot_ly(x = ~value, 
          y = ~edad,
          type = 'bar',
          orientation = 'h',
          marker = ~list(color = ifelse(sexo == "V", "#c2a6c2","#efcf83"))
)  %>% 
  layout(
    #title = "1914",
      yaxis = list(title = 'grupos quinquenales'), 
      xaxis = list(title = ' ', range= c(-10,10)),
      showlegend = FALSE
  )

pi1914


pi2022 <- datasies %>% 
  filter(censo == 2022) %>% 
  plot_ly(x = ~value, 
          y = ~edad,
          type = 'bar',
          orientation = 'h',
          marker = ~list(color = ifelse(sexo == "V", "#9D719E","#E6B43D"))
)  %>% 
  layout(
    #title = "2022",
      yaxis = list(title = 'grupos quinquenales'), 
      xaxis = list(title = ' ', range= c(-10,10)),
      showlegend = FALSE
  )

pi2022

```


```{r eval=FALSE, include=FALSE}

fig <- subplot(
  pi1914, pi2022, 
  shareY = TRUE,
  #margin = 0.15,
  nrows = 1) %>% 
  layout(
    # width = 900, height = 500
    annotations =  
      list(
        list(
          x = 0.2,  
    y = 1.0,  
    text = "1914",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE),
        list(
           x = 0.8,  
    y = 1,  
    text = "2022",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE )
          )
    
        )
fig
```



```{r fig.width= 10, fig.height= 6}
pi <- 
  datasies %>% 
  mutate(sexo =  ifelse(sexo == "V", "varones", "mujeres")) %>% 
  rename(porcentaje = value) %>% 
  ggplot(aes(x = porcentaje, y = edad, fill = sexo,  
             text = paste("porcentaje:", ifelse(sexo == "varones", porcentaje*(-1), porcentaje), "%"))) +
  geom_col() +
  facet_wrap(~censo) +
  scale_fill_manual(values = c("#9D719E","#E6B43D")) +
  scale_x_continuous(breaks = seq(-10, 10, by = 2), 
                     labels = paste0(c(seq(-10, 0, by = 2)*-1, seq(2, 10, by = 2)), "%")) +
  labs(
    x = "porcentaje",
    y = "grupo de edad"
  ) +
  theme_bw() #+ theme(legend.position="bottom", legend.title = element_blank())

ggplotly(pi, tooltip = c("text", "sexo", "edad")) %>% layout(legend = list(orientation = 'h'))


```


```{r}
piramide <- 
ggplotly(pi, tooltip = c("text", "sexo", "edad")) %>% layout(legend = list(orientation = 'h'))

qsave(piramide, "piramide.qs")
```

